name: Server Port
main: com.raphfrk.bukkit.serverport.ServerPortBukkit
version: 388
commands:
  worldlist:
    description:
    usage:
  stell:
    description:
    usage:
  stime:
    description:
    usage:
  listinv:
    description:
    usage:
  stime:
    description:
    usage:
  pos:
    description:
    usage:
  refresh:
    description:
    usage:
  usegate:
    description:
    usage:
  itemgen:
    description:
    usage:
  release:
    description:
    usage:
  getinv:
    description:
    usage:
  serverport:
    description:
    usage:
  drawgate:
    description:
    usage:
  cancelredirect:
    description:
    usage:
  regengates:
    description:
    usage:
  stopcircle:
    description:
    usage:
  circleload:
    description:
    usage:
softdepend:
  - Permissions
