#!/usr/bin/bash

 ./updatr sptwo ServerPort

pushd ..

git remote add origin git@github.com:Raphfrk/ServerPort.git
git push origin master

popd


cat patchersafecopy version.txt patcherfilename | /usr/bin/bash

